//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalismansGen.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TalismansGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 SS	3-1-1
        ///SA	3-1-1
        ///SB	3-1-1
        ///SC	3-1-1
        ///S	3-1-1
        ///AS	3-1-1
        ///AA	3-1-1
        ///AB	3-1-1
        ///AC	3-1-1
        ///A	3-1-1
        ///BS	3-1-1
        ///BA	3-1-1
        ///BB	3-2-1
        ///BC	3-2-1
        ///B	3-2-1
        ///CS	3-1-1
        ///CA	3-1-1
        ///CB	3-2-1
        ///CC	3-2-1
        ///C	3-2-1 的本地化字符串。
        /// </summary>
        internal static string levelHoleMap {
            get {
                return ResourceManager.GetString("levelHoleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 攻击 A 3 2
        ///2 挑战者 A 3 2
        ///3 无伤 A 2 2
        ///4 怨恨 A 3 2
        ///5 死里逃生 A 2 2
        ///6 看破 A 3 2
        ///7 超会心 S 2 1
        ///8 弱点特效 A 2 2
        ///9 力量解放 A 3 2
        ///10 精神抖擞 A 2 2
        ///11 会心击【属性】 A 2 2
        ///13 火属性攻击强化 B 3 2
        ///14 水属性攻击强化 B 3 2
        ///15 冰属性攻击强化 B 3 2
        ///16 雷属性攻击强化 B 3 2
        ///17 龙属性攻击强化 B 3 2
        ///18 毒属性强化 B 3 2
        ///19 麻痹属性强化 A 2 2
        ///20 睡眠属性强化 A 2 2
        ///21 爆破属性强化 A 2 2
        ///22 匠 S 2 1
        ///23 利刃 A 2 2
        ///24 弹丸节约 A 2 2
        ///25 刚刃打磨 A 2 2
        ///26 心眼 S 2 1
        ///27 弹道强化 A 2 2
        ///28 钝器能手 B 3 2
        ///30 集中 S 2 1
        ///31 强化持续 A 2 2
        ///32 跑者 S 2 1
        ///33 体术 C 3 3
        ///34 耐力急速回复 A 2 2
        ///35 防御性能 A 3 2
        ///36 防御强化 A 2 2
        ///37 攻击守势 S 2 1
        ///38 拔刀术【技】 S 2 1
        ///39 拔刀术【力】 B [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string skill {
            get {
                return ResourceManager.GetString("skill", resourceCulture);
            }
        }
    }
}
